name: flutter_app_picture_analysis
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  # camera
  camera: ^0.4.0+1

  # path_provider
  path_provider: ^0.5.0+1

  # http
  http: ^0.12.0+1

  # firebase ml vision
  # firebase_ml_vision: ^0.5.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/flutter-logo.png
